# Generated by Django 4.2.26 on 2025-11-25 05:46

import accounts.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('Junior', 'Junior'), ('Senior', 'Senior'), ('PC', 'Placement Coordinator'), ('HR', 'HR Representative')], default='Junior', max_length=20)),
                ('year', models.IntegerField(default=1)),
                ('roll_number', models.CharField(blank=True, max_length=50, null=True)),
                ('college', models.CharField(blank=True, max_length=200)),
                ('cgpa', models.FloatField(default=0.0)),
                ('skills', models.TextField(default=accounts.models.default_skills)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
