# Generated by Django 4.2.26 on 2025-12-01 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_liveplacement'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LivePlacement',
        ),
    ]
