# Generated by Django 4.2.26 on 2025-12-01 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0003_delete_liveplacement'),
    ]

    operations = [
        migrations.CreateModel(
            name='LivePlacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=200)),
                ('role', models.CharField(max_length=200)),
                ('package_lpa', models.FloatField()),
                ('location', models.CharField(max_length=200)),
                ('mode', models.CharField(choices=[('ON_CAMPUS', 'On-Campus'), ('POOL_CAMPUS', 'Pool Campus'), ('OFF_CAMPUS', 'Off-Campus')], max_length=20)),
                ('category', models.CharField(choices=[('PRODUCT', 'Product'), ('SERVICE', 'Service'), ('IT', 'IT')], max_length=20)),
                ('placed_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.company')),
            ],
        ),
    ]
